/* The following code was generated by JFlex 1.4.3 on 09-6-26 下午9:46 */

package dbrocks.frontend;

import dbrocks.util.Location;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 09-6-26 下午9:46 from the specification file
 * <tt>src/dbrocks/frontend/Lexer.l</tt>
 */
public class Lexer extends LexerBase {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int IN_QUOTE = 2;
  public static final int YYINITIAL = 0;
  public static final int IN_APOS = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\17\1\2\2\0\1\1\22\0\1\17\1\16\1\41\2\0"+
    "\1\12\2\0\1\12\1\12\1\12\1\11\1\12\1\6\1\4\1\12"+
    "\12\3\1\0\1\12\1\14\1\13\1\15\2\0\4\7\1\5\25\7"+
    "\1\12\1\42\1\12\1\0\1\10\1\0\1\36\1\37\1\23\1\35"+
    "\1\21\1\25\1\7\1\32\3\7\1\22\1\30\1\40\1\27\1\34"+
    "\1\7\1\26\1\20\1\24\1\33\1\7\1\31\3\7\1\12\1\0"+
    "\1\12\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\5\4\4\1\2"+
    "\10\5\1\6\1\7\2\10\1\11\1\7\1\12\1\0"+
    "\1\13\1\14\1\15\5\5\1\16\4\5\1\17\1\5"+
    "\1\20\1\21\1\22\1\23\1\24\1\0\1\5\1\25"+
    "\10\5\1\26\1\0\1\5\1\27\1\5\1\30\4\5"+
    "\1\31\1\12\1\5\1\32\1\33\1\34\2\5\1\35"+
    "\1\36\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
	@SuppressWarnings("unused")
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
	@SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	private Location sloc = null;
	private StringBuilder buffer = new StringBuilder();

	public Location getLocation() {
		return new Location(yyline + 1, yycolumn + 1);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 124) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;


    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          zzInput = zzCMapL[zzInput];

          boolean zzIsFinal = false;
          boolean zzNoLookAhead = false;

          zzForNext: { switch (zzState) {
            case 0:
              switch (zzInput) {
                case 0: 
                case 8: 
                case 34: zzIsFinal = true; zzNoLookAhead = true; zzState = 3; break zzForNext;
                case 1: zzIsFinal = true; zzState = 4; break zzForNext;
                case 2: zzIsFinal = true; zzNoLookAhead = true; zzState = 5; break zzForNext;
                case 3: zzIsFinal = true; zzState = 6; break zzForNext;
                case 4: 
                case 9: 
                case 10: 
                case 11: zzIsFinal = true; zzNoLookAhead = true; zzState = 7; break zzForNext;
                case 6: zzIsFinal = true; zzState = 9; break zzForNext;
                case 12: zzIsFinal = true; zzState = 10; break zzForNext;
                case 13: zzIsFinal = true; zzState = 11; break zzForNext;
                case 14: zzIsFinal = true; zzState = 12; break zzForNext;
                case 15: zzIsFinal = true; zzState = 13; break zzForNext;
                case 16: zzIsFinal = true; zzState = 14; break zzForNext;
                case 20: zzIsFinal = true; zzState = 15; break zzForNext;
                case 21: zzIsFinal = true; zzState = 16; break zzForNext;
                case 23: zzIsFinal = true; zzState = 17; break zzForNext;
                case 25: zzIsFinal = true; zzState = 18; break zzForNext;
                case 27: zzIsFinal = true; zzState = 19; break zzForNext;
                case 29: zzIsFinal = true; zzState = 20; break zzForNext;
                case 30: zzIsFinal = true; zzState = 21; break zzForNext;
                case 33: zzIsFinal = true; zzNoLookAhead = true; zzState = 22; break zzForNext;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 1:
              switch (zzInput) {
                case 1: zzIsFinal = true; zzState = 24; break zzForNext;
                case 2: zzIsFinal = true; zzNoLookAhead = true; zzState = 25; break zzForNext;
                case 33: zzIsFinal = true; zzNoLookAhead = true; zzState = 26; break zzForNext;
                case 34: zzIsFinal = true; zzState = 27; break zzForNext;
                default: zzIsFinal = true; zzNoLookAhead = true; zzState = 23; break zzForNext;
              }

            case 4:
              switch (zzInput) {
                case 2: zzIsFinal = true; zzNoLookAhead = true; zzState = 5; break zzForNext;
                default: break zzForAction;
              }

            case 6:
              switch (zzInput) {
                case 3: zzIsFinal = true; break zzForNext;
                case 4: zzIsFinal = true; zzState = 28; break zzForNext;
                default: break zzForAction;
              }

            case 8:
              switch (zzInput) {
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; break zzForNext;
              }

            case 9:
              switch (zzInput) {
                case 6: zzState = 29; break zzForNext;
                default: break zzForAction;
              }

            case 10:
              switch (zzInput) {
                case 11: zzIsFinal = true; zzNoLookAhead = true; zzState = 30; break zzForNext;
                default: break zzForAction;
              }

            case 11:
              switch (zzInput) {
                case 11: zzIsFinal = true; zzNoLookAhead = true; zzState = 31; break zzForNext;
                default: break zzForAction;
              }

            case 12:
              switch (zzInput) {
                case 11: zzIsFinal = true; zzNoLookAhead = true; zzState = 32; break zzForNext;
                default: break zzForAction;
              }

            case 13:
              switch (zzInput) {
                case 15: zzIsFinal = true; break zzForNext;
                default: break zzForAction;
              }

            case 14:
              switch (zzInput) {
                case 17: zzIsFinal = true; zzState = 33; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 15:
              switch (zzInput) {
                case 22: zzIsFinal = true; zzState = 34; break zzForNext;
                case 30: zzIsFinal = true; zzState = 35; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 16:
              switch (zzInput) {
                case 22: zzIsFinal = true; zzState = 36; break zzForNext;
                case 30: zzIsFinal = true; zzState = 37; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 17:
              switch (zzInput) {
                case 22: zzIsFinal = true; zzState = 38; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 18:
              switch (zzInput) {
                case 26: zzIsFinal = true; zzState = 39; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 19:
              switch (zzInput) {
                case 28: zzIsFinal = true; zzState = 40; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 20:
              switch (zzInput) {
                case 17: zzIsFinal = true; zzState = 41; break zzForNext;
                case 22: zzIsFinal = true; zzState = 42; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 21:
              switch (zzInput) {
                case 16: zzIsFinal = true; zzState = 43; break zzForNext;
                case 32: zzIsFinal = true; zzState = 44; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 24:
              switch (zzInput) {
                case 2: zzIsFinal = true; zzNoLookAhead = true; zzState = 25; break zzForNext;
                default: break zzForAction;
              }

            case 27:
              switch (zzInput) {
                case 20: zzIsFinal = true; zzNoLookAhead = true; zzState = 45; break zzForNext;
                case 22: zzIsFinal = true; zzNoLookAhead = true; zzState = 46; break zzForNext;
                case 32: zzIsFinal = true; zzNoLookAhead = true; zzState = 47; break zzForNext;
                case 33: zzIsFinal = true; zzNoLookAhead = true; zzState = 48; break zzForNext;
                case 34: zzIsFinal = true; zzNoLookAhead = true; zzState = 49; break zzForNext;
                default: break zzForAction;
              }

            case 28:
              switch (zzInput) {
                case 3: zzIsFinal = true; break zzForNext;
                case 5: 
                case 17: zzState = 50; break zzForNext;
                default: break zzForAction;
              }

            case 29:
              switch (zzInput) {
                case 1: zzIsFinal = true; zzState = 4; break zzForNext;
                case 2: zzIsFinal = true; zzNoLookAhead = true; zzState = 5; break zzForNext;
                default: break zzForNext;
              }

            case 33:
              switch (zzInput) {
                case 18: zzIsFinal = true; zzState = 51; break zzForNext;
                case 20: zzIsFinal = true; zzState = 52; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 34:
              switch (zzInput) {
                case 27: zzIsFinal = true; zzState = 53; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 35:
              switch (zzInput) {
                case 31: zzIsFinal = true; zzState = 54; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 36:
              switch (zzInput) {
                case 23: zzIsFinal = true; zzState = 55; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 37:
              switch (zzInput) {
                case 18: zzIsFinal = true; zzState = 56; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 38:
              switch (zzInput) {
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 39:
              switch (zzInput) {
                case 17: zzIsFinal = true; zzState = 57; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 40:
              switch (zzInput) {
                case 29: zzIsFinal = true; zzState = 58; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 41:
              switch (zzInput) {
                case 18: zzIsFinal = true; zzState = 59; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 42:
              switch (zzInput) {
                case 23: zzIsFinal = true; zzState = 60; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 43:
              switch (zzInput) {
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 44:
              switch (zzInput) {
                case 29: zzIsFinal = true; zzState = 61; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 50:
              switch (zzInput) {
                case 6: 
                case 9: zzState = 62; break zzForNext;
                default: break zzForAction;
              }

            case 51:
              switch (zzInput) {
                case 17: zzIsFinal = true; zzState = 63; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 52:
              switch (zzInput) {
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 53:
              switch (zzInput) {
                case 17: zzIsFinal = true; zzState = 64; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 54:
              switch (zzInput) {
                case 18: zzIsFinal = true; zzState = 65; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 55:
              switch (zzInput) {
                case 24: zzIsFinal = true; zzState = 66; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 56:
              switch (zzInput) {
                case 16: zzIsFinal = true; zzState = 67; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 57:
              switch (zzInput) {
                case 22: zzIsFinal = true; zzState = 68; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 58:
              switch (zzInput) {
                case 30: zzIsFinal = true; zzState = 69; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 59:
              switch (zzInput) {
                case 17: zzIsFinal = true; zzState = 70; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 60:
              switch (zzInput) {
                case 28: zzIsFinal = true; zzState = 71; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 61:
              switch (zzInput) {
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 62:
              switch (zzInput) {
                case 3: zzIsFinal = true; zzState = 72; break zzForNext;
                default: break zzForAction;
              }

            case 63:
              switch (zzInput) {
                case 19: zzIsFinal = true; zzState = 73; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 64:
              switch (zzInput) {
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 65:
              switch (zzInput) {
                case 17: zzIsFinal = true; zzState = 74; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 66:
              switch (zzInput) {
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 67:
              switch (zzInput) {
                case 17: zzIsFinal = true; zzState = 75; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 68:
              switch (zzInput) {
                case 17: zzIsFinal = true; zzState = 76; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 69:
              switch (zzInput) {
                case 20: zzIsFinal = true; zzState = 77; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 70:
              switch (zzInput) {
                case 20: zzIsFinal = true; zzState = 78; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 71:
              switch (zzInput) {
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 72:
              switch (zzInput) {
                case 3: zzIsFinal = true; break zzForNext;
                default: break zzForAction;
              }

            case 73:
              switch (zzInput) {
                case 20: zzIsFinal = true; zzState = 79; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 74:
              switch (zzInput) {
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 75:
              switch (zzInput) {
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 76:
              switch (zzInput) {
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 77:
              switch (zzInput) {
                case 17: zzIsFinal = true; zzState = 80; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 78:
              switch (zzInput) {
                case 17: zzIsFinal = true; zzState = 81; break zzForNext;
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 79:
              switch (zzInput) {
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 80:
              switch (zzInput) {
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            case 81:
              switch (zzInput) {
                case 0: 
                case 1: 
                case 2: 
                case 4: 
                case 6: 
                case 9: 
                case 10: 
                case 11: 
                case 12: 
                case 13: 
                case 14: 
                case 15: 
                case 33: 
                case 34: break zzForAction;
                default: zzIsFinal = true; zzState = 8; break zzForNext;
              }

            default:
              // if this is ever reached, there is a serious bug in JFlex
              zzScanError(ZZ_UNKNOWN_ERROR);
              break;
          } }

          if ( zzIsFinal ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( zzNoLookAhead ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 23: 
          { return booleanConst(true);
          }
        case 32: break;
        case 16: 
          { buffer.append('\t');
          }
        case 33: break;
        case 28: 
          { return keyword(Parser.WHERE);
          }
        case 34: break;
        case 19: 
          { buffer.append('"');
          }
        case 35: break;
        case 18: 
          { buffer.append('\n');
          }
        case 36: break;
        case 1: 
          { /* issueError(new UnrecogCharError(getLocation(), yycharat(0)));*/
          }
        case 37: break;
        case 3: 
          { return intConst(yytext());
          }
        case 38: break;
        case 29: 
          { return keyword(Parser.SELECT);
          }
        case 39: break;
        case 6: 
          { sloc = getLocation();		  
						yybegin(IN_QUOTE);
						buffer = new StringBuilder();
          }
        case 40: break;
        case 10: 
          { return doubleConst(yytext());
          }
        case 41: break;
        case 30: 
          { return keyword(Parser.UPDATE);
          }
        case 42: break;
        case 27: 
          { return booleanConst(false);
          }
        case 43: break;
        case 20: 
          { buffer.append('\\');
          }
        case 44: break;
        case 31: 
          { return keyword(Parser.DELETE);
          }
        case 45: break;
        case 24: 
          { return keyword(Parser.FROM);
          }
        case 46: break;
        case 11: 
          { return operator(Parser.LESS_EQUAL);
          }
        case 47: break;
        case 2: 
          { /* Just ignore */
          }
        case 48: break;
        case 4: 
          { return operator((int) yycharat(0));
          }
        case 49: break;
        case 14: 
          { return operator(Parser.LOGIC_OR);
          }
        case 50: break;
        case 26: 
          { return keyword(Parser.TABLE);
          }
        case 51: break;
        case 17: 
          { buffer.append('\r');
          }
        case 52: break;
        case 8: 
          { /*issueError(new NewlineInStrError(sloc, MiscUtils.quote(buffer.toString())))*/
          }
        case 53: break;
        case 12: 
          { return operator(Parser.GREATER_EQUAL);
          }
        case 54: break;
        case 15: 
          { return keyword(Parser.AS);
          }
        case 55: break;
        case 22: 
          { return operator(Parser.LOGIC_AND);
          }
        case 56: break;
        case 13: 
          { return operator(Parser.NOT_EQUAL);
          }
        case 57: break;
        case 7: 
          { buffer.append(yytext());
          }
        case 58: break;
        case 21: 
          { return keyword(Parser.SET);
          }
        case 59: break;
        case 9: 
          { yybegin(YYINITIAL);
					  		return stringConst(buffer.toString(), sloc);
          }
        case 60: break;
        case 25: 
          { return keyword(Parser.DROP);
          }
        case 61: break;
        case 5: 
          { return identifier(yytext());
          }
        case 62: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case IN_QUOTE: {
              /*issueError(new UntermStrError(sloc, MiscUtils.quote(buffer.toString())));*/
					  		yybegin(YYINITIAL);
            }
            case 83: break;
            default:
              { return 0; }
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
