#!/usr/bin/env python

import os
import sys
import pkg_resources

if (sys.version_info.major, sys.version_info.minor) != (2, 7):
    raise NotImplementedError("Python 2.7 required")

BOTTLE = "bottle-0.12.8"
GLANCES = "glances-2.4.2"
NETIFACES = "netifaces-0.10.4"
PSUTIL = "psutil-3.0.1"

SCRIPT_ROOT = os.path.abspath(os.path.split(__file__)[0])

sys.path += os.path.join(SCRIPT_ROOT, GLANCES),
PSUTIL_PATH = os.path.join(SCRIPT_ROOT, PSUTIL, "build", "lib." + pkg_resources.get_build_platform() + "-2.7")
sys.path += PSUTIL_PATH,
sys.path += os.path.join(SCRIPT_ROOT, BOTTLE),
NETIFACES_PATH = os.path.join(SCRIPT_ROOT, NETIFACES, "build", "lib." + pkg_resources.get_build_platform() + "-2.7")
sys.path += NETIFACES_PATH,

def main():
    os.chdir(SCRIPT_ROOT)

    if not os.path.exists(PSUTIL_PATH):
        print "Building psutil"
        os.system("cd %s; python setup.py build > /dev/null 2>&1" % PSUTIL)

    if not os.path.exists(NETIFACES_PATH):
        print "Building netifaces"
        os.system("cd %s; python setup.py build > /dev/null 2>&1" % NETIFACES)

    import glances
    glances.main()

if __name__ == "__main__":
    main()
