#!/usr/bin/env python

import os
import sys
import pkg_resources

# Require Python 2
assert sys.version_info[0] == 2

BOTTLE = "bottle-0.12.8"
GLANCES = "glances-2.4.2"
NETIFACES = "netifaces-0.10.4"
PSUTIL = "psutil-3.2.1"
LOGUTILS = "logutils-0.3.3"

SCRIPT_ROOT = os.path.abspath(os.path.split(__file__)[0])

PYVER = "-%d.%d" % (sys.version_info[0], sys.version_info[1])

sys.path += os.path.join(SCRIPT_ROOT, GLANCES),
PSUTIL_PATH = os.path.join(SCRIPT_ROOT, PSUTIL, "build", "lib." + pkg_resources.get_build_platform() + PYVER)
sys.path += PSUTIL_PATH,
sys.path += os.path.join(SCRIPT_ROOT, BOTTLE),
NETIFACES_PATH = os.path.join(SCRIPT_ROOT, NETIFACES, "build", "lib." + pkg_resources.get_build_platform() + PYVER)
sys.path += NETIFACES_PATH,
sys.path += os.path.join(SCRIPT_ROOT, LOGUTILS),

def main():
    os.chdir(SCRIPT_ROOT)

    if not os.path.exists(PSUTIL_PATH):
        print "Building psutil"
        os.system("cd %s; python setup.py build > /dev/null 2>&1" % PSUTIL)

    if not os.path.exists(NETIFACES_PATH):
        print "Building netifaces"
        os.system("cd %s; PYTHONPATH=../setuptools-18.2:$PYTHONPATH python setup.py build > /dev/null 2>&1" % NETIFACES)

    import glances
    glances.main()

if __name__ == "__main__":
    main()
