# Even Fibonacci numbers
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

fib = [1, 2]
loop do
  next_fib = fib[-2] + fib[-1]
  break if next_fib > 4_000_000
  fib << next_fib
end

puts fib.select{ |n| n.even? }.inject{ |s, n| s += n }
