#!/usr/bin/env python
#
# Wrapper around waf-light
#
# Yang Zhang <y@yzhang.net>, 2015
# See LICENSE file for copyright notice

import os
import subprocess
import sys

os.chdir(os.path.dirname(os.path.abspath(__file__)))
waf = "deps/waf-1.8.21/waf-light"
exit(subprocess.call([sys.executable, waf] + sys.argv[1:]))
