import os
import sys
sys.path = [os.path.abspath("./scripts/waf_utils")] + sys.path

import waf_commands

APPNAME = "geopipe-stuff"
from waflib import Logs

def options(opt):
    opt.load("compiler_c")
    opt.load("compiler_cxx")
    opt.load("waf_default", tooldir="./scripts/waf_utils")

def configure(conf):
    conf.load("compiler_c")
    conf.load("compiler_cxx")
    conf.load("waf_default", tooldir="./scripts/waf_utils")

def build(bld):
    if bld.cmd == "build":
        waf_commands.MakefileGen().execute()
