import os
import sys
sys.path = [os.path.abspath("./scripts/waf_utils")] + sys.path

import waf_commands

APPNAME = "geopipe-stuff"
from waflib import Logs


def options(opt):
    opt.load("compiler_c")
    opt.load("compiler_cxx")
    opt.load("waf_default", tooldir="./scripts/waf_utils")


def configure(conf):
    conf.load("compiler_c")
    conf.load("compiler_cxx")
    conf.load("waf_default", tooldir="./scripts/waf_utils")

    src_dir = conf.srcnode.abspath()
    deps_dir = os.path.join(src_dir, "deps")
    deps_install_dir = os.path.join(deps_dir, "_install")
    deps_install_include_dir = os.path.join(deps_install_dir, "include")
    deps_install_lib_dir = os.path.join(deps_install_dir, "lib")

    conf.env.append_value("CXXFLAGS", ["-isystem", deps_dir])
    conf.env.append_value("CXXFLAGS", ["-isystem", deps_install_include_dir])
    conf.env.append_value("LINKFLAGS", ["-L", deps_install_lib_dir])

    # for caffe
    conf.env.append_value("CXXFLAGS", ["-isystem", os.path.join(deps_dir, "_build/caffe/build/src")])
    conf.env.append_value("CXXFLAGS", ["-isystem", os.path.join(deps_dir, "_build/caffe/include")])
    conf.env.append_value("CXXFLAGS", ["-isystem", "/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers/"])
    conf.env.append_value("LINKFLAGS", ["-L", os.path.join(deps_dir, "_build/caffe/build/lib")])
    conf.env.append_value("DEFINES", ["CPU_ONLY"])

    conf.env.LIB_LASLIB = "las"
    conf.env.LIB_GFLAGS = "gflags"
    conf.env.LIB_CAFFE = "caffe"
    conf.env.LIB_GLOG = "glog"
    conf.env.LIB_PROTOBUF = "protobuf"
    conf.env.LIB_BOOST_SYSTEM = "boost_system"
    conf.env.LIB_OPENCV_CORE = "opencv_core"
    conf.env.LIB_OPENCV_HIGHGUI = "opencv_highgui"


def build(bld):
    if bld.cmd == "build":
        waf_commands.MakefileGen().execute()

    bld.stlib(source=bld.path.ant_glob("deps/gtest/*.cc"),
              target="gtest_main")

    bld.program(source=bld.path.ant_glob("test/test-*.cc"),
                target="t",
                use="gtest_main LASLIB")

    bld.program(source=bld.path.ant_glob("las2img/*.cc"),
                target="las2img.bin",
                includes=".",
                use="LASLIB GFLAGS")

    bld.stlib(source=bld.path.ant_glob("find_trees/*.cpp find_trees/*.cc find_trees/*.c", excl="find_trees/main.cc"),
              target="find_trees",
              use="CAFFE GLOG PROTOBUF BOOST_SYSTEM")

    bld.program(source="find_trees/main.cc",
                target="find_trees.bin",
                includes=".",
                use="find_trees GFLAGS OPENCV_CORE OPENCV_HIGHGUI")
