#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
# Resolve $SOURCE until the file is no longer a symlink
while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    # If $SOURCE was a relative symlink, we need to resolve it relative to the
    # path where the symlink file was located
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# export LD_DEBUG=files,statistics

# https://github.com/hadolint/hadolint/issues/173#issuecomment-372479773
export LC_ALL=C.UTF-8

LD_LIBRARY_PATH=$DIR/.run_anywhere_payload:$LD_LIBRARY_PATH exec $DIR/.run_anywhere_payload/ld-linux-x86-64.so.2 --inhibit-cache --inhibit-rpath $DIR/.run_anywhere_payload/lua.run_anywhere_real_binary $DIR/.run_anywhere_payload/lua.run_anywhere_real_binary "$@"
