.PHONY: all clean

DEVSTUFF_ROOT=${HOME}/Workspace/devstuff

all: folly_demo

folly_demo: folly_demo.o
	g++ $^ ${DEVSTUFF_ROOT}/lib/libfolly.a /usr/lib/x86_64-linux-gnu/libboost_system.a \
		/usr/lib/x86_64-linux-gnu/libboost_filesystem.a \
		/usr/lib/x86_64-linux-gnu/libboost_context.a \
		/usr/lib/x86_64-linux-gnu/libdouble-conversion.a \
		/usr/lib/x86_64-linux-gnu/libglog.a /usr/lib/x86_64-linux-gnu/libgflags.a \
		/usr/lib/x86_64-linux-gnu/libunwind.a /usr/lib/x86_64-linux-gnu/liblzma.a \
		/usr/lib/x86_64-linux-gnu/libevent.a \
		-lpthread -ldl \
		-o $@
	ldd -v $@

folly_demo.o: folly_demo.cc
	g++ -std=c++0x -I${DEVSTUFF_ROOT}/include -c $^ -o $@

clean:
	rm -f *.o folly_demo
